In [9]:
import numpy as pd
A_23 = pd.array([11,12,13,14,15])
print(a_23)

[11 12 13 14 15]


In [12]:
B_23 = pd.array([[15,26,65,45],[45,6,12,7]])
print(b_25)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
C_23= pd.array([[[10,5,27,56],[12,23,14,90],[19,29,43,67]]])
print(C_23)    

[[[10  5 27 56]
  [12 23 14 90]
  [19 29 43 67]]]


In [30]:
A_23= pd.array ([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(A_23)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [33]:
B_23 = [1,2]